# Vetores reshape 2

In [1]:
# Crie um vetor de tamanho 9 com valores aleatórios e use o reshape para transformá-lo em uma matriz 3x3.

import numpy as np
 
# Criando o vetor (1x9)
vetor = np.random.randint(1,10,9)
print(f"Antes:\n {vetor}")

# Reshape no vetor (3x3)
vetor = vetor.reshape(3,3)
print(f"Após:\n {vetor}")


Antes:
 [5 5 7 1 5 2 3 7 8]
Após:
 [[5 5 7]
 [1 5 2]
 [3 7 8]]
