# Vetores reshape

In [1]:
# Crie um vetor de tamanho 6 com valores aleatórios. Use o reshape para transformá-lo em uma matriz 2x3.

import numpy as np
 
# Criando o vetor (1x6)
vetor = np.random.randint(1,10,6)
print(f"Antes:\n {vetor}")

# Reshape (2x3)
vetor = vetor.reshape(2,3)
print(f"Após:\n {vetor}")

Antes:
 [9 1 8 1 9 6]
Após:
 [[9 1 8]
 [1 9 6]]
