# Reorganização

In [1]:
# Criar um vetor de tamanho 12 e separá-lo em 3 vetores de tamanho 4.
import numpy as np

# Criando o vetor
vetor = np.random.randint(1,10,12)
print(f"Antes da reorganização:\n{vetor}")

# Substituindo
vetor = vetor.reshape(3,4)
print(f"\nApós:\n{vetor}")

Antes da reorganização:
[4 3 3 4 5 2 4 9 1 9 9 7]

Após:
[[4 3 3 4]
 [5 2 4 9]
 [1 9 9 7]]
