# Mascaras

In [3]:
# Criar um vetor aleatório de tamanho 15 e dividir os elementos em dois grupos: negativos e positivos.

import numpy as np

# Criando o vetor
vetor = np.random.randint(-50,50,15)
print(f"Antes da reorganização:\n{vetor}")

# Máscaras
m_positivo = vetor > 0
m_negativo = vetor < 0

print(f"Após a máscara positiva:\n{vetor[m_positivo]}")
print(f"Após a máscara negativa:\n{vetor[m_negativo]}")

Antes da reorganização:
[ 44 -50  -4  29  27  40  35 -19 -36 -47 -19 -45  21  26  45]
Após a máscara positiva:
[44 29 27 40 35 21 26 45]
Após a máscara negativa:
[-50  -4 -19 -36 -47 -19 -45]
