# Vetores concatenados 2

In [3]:
# Crie dois vetores 1D e empilhe-os verticalmente para formar uma matriz 2D.

# Criando os vetores
import numpy as np
vetor1 = np.random.randint(1,10,5)
vetor2 = np.random.randint(1,10,5)
print(f"Antes vetor 1:\n{vetor1}")
print(f"Antes vetor 2:\n{vetor2}")


# Concatenando verticalmente
vetor_concatenado = np.vstack((vetor1, vetor2))
print(f"\nNovo vetor concatenado verticalmente:\n {vetor_concatenado}")

Antes vetor 1:
[8 1 4 6 1]
Antes vetor 2:
[6 4 8 8 1]

Novo vetor concatenado verticalmente:
 [[8 1 4 6 1]
 [6 4 8 8 1]]
