# Vetores Transpostos

In [ ]:
#  Crie um vetor de tamanho 5 com valores aleatórios entre 1 e 10. Obtenha o vetor transposto (transforme o vetor em uma coluna) e mostre o resultado.
import numpy as np
vetor = np.array([[1,2,3], [4,5,6]])
print(f"Antes:\n{vetor}")

# Transpondo o vetor (Inverter suas dimensões (2x3) -> (3x2) )
vetor_t = vetor.T
print(f"Após:\n {vetor_t}")


Antes:
[[1 2 3]
 [4 5 6]]
Após:
 [[1 4]
 [2 5]
 [3 6]]
