# Vetores reshape 3

In [1]:
# Crie um vetor de tamanho 12 com valores aleatórios. Transforme-o em uma matriz 3x4 e depois transforme essa matriz de volta em um vetor.


import numpy as np
 
# Criando o vetor (1x12)
vetor = np.random.randint(1,10,12)
print(f"Antes:\n {vetor}")

# Reshape no vetor (3x4)
vetor = vetor.reshape(3,4) # Os valores de reshape tem que ser linha x coluna = quantidade de elementos, caso contrario vai dar errado!
print(f"Após:\n {vetor}")

Antes:
 [2 3 9 7 2 9 9 5 7 8 1 3]
Após:
 [[2 3 9 7]
 [2 9 9 5]
 [7 8 1 3]]
