# Vetor concatenado 3

In [19]:
# Crie dois vetores 1D, vetor1 e vetor2, ambos com 5 elementos, e os concatene para formar um único vetor.


# Criando os vetores
import numpy as np
vetor1 = np.random.randint(1,10,5)
vetor2 = np.random.randint(1,10,5)
print(f"Antes vetor 1:\n{vetor1}")
print(f"Antes vetor 2:\n{vetor2}")


# Concatenando
vetor_horizontal = np.hstack((vetor1, vetor2))
vetor_vertical = np.vstack((vetor1, vetor2))
print(f"\nApós vetor horizontal:\n{vetor_horizontal}")
print(f"\nApós vetor vertical:\n{vetor_vertical}")

Antes vetor 1:
[3 3 9 4 3]
Antes vetor 2:
[5 1 8 6 3]

Após vetor horizontal:
[3 3 9 4 3 5 1 8 6 3]

Após vetor vertical:
[[3 3 9 4 3]
 [5 1 8 6 3]]
