# Vetores transpostos 2

In [3]:
import numpy as np

vetor_linha = np.array([ [1,2,3], [4,5,6] ]) # (2x3) -> (3x2)

vetor_coluna = vetor_linha.T  
print(f"Antes:\n {vetor_linha}")
print(f"Após:\n {vetor_coluna}")


Antes:
 [[1 2 3]
 [4 5 6]]
Após:
 [[1 4]
 [2 5]
 [3 6]]
