In [ ]:
# Inverter um vetor usando sciling
import numpy as np 
# Criação do vetor com números aleatórios de 1-101 com 20 elementos
vetor = np.random.randint(1, 101, 10)
print(f"O vetor original é de:\n{vetor}\n\n")

# Inversão do vetor usando o sciling
vetor = vetor[::-1]
print(f"O vetor invertido é de:\n{vetor}")

O vetor original é de:
[38 23 39 30 99 36 32 72 42 54]


O vetor invertido é de:
[54 42 72 32 36 99 30 39 23 38]


In [5]:
# Tambem podemos usar a técnica flip do próprio numpy
import numpy as np 
# Criação do vetor com números aleatórios de 1-101 com 20 elementos
vetor2 = np.random.randint(1, 101, 10)
print(f"O vetor original é de:\n{vetor2}\n\n")

# Inversão do vetor usando o sciling
vetor2 = np.flip(vetor2)
print(f"O vetor invertido é de:\n{vetor2}")

O vetor original é de:
[14 32 99 73 30 43 58  9 89 53]


O vetor invertido é de:
[53 89  9 58 43 30 73 99 32 14]
