# Indexação

In [3]:
# Dado uma matriz 3x3 de 1 até 9, printe toda a última linha

import numpy as np

# Criando a matriz
matriz = np.array([ [1,2,3], [4,5,6], [7,8,9]])
print(f"A matriz criada foi:\n{matriz}")
print(f"Acessando a ultima linha inteira: {matriz[2, :]}")

A matriz criada foi:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Acessando a ultima linha inteira: [7 8 9]
