# Indexação

In [ ]:
# Dado uma matriz 3x3, acesse todo os elementos a partir da 1 linha e 2 coluna

import numpy as np

# Criando a matriz
matriz = np.array([ [1,2,3], [4,5,6], [7,8,9]])
print(f"A matriz criada foi:\n{matriz}")
print(f"Acessando a partir da 1 linha e 2 coluna: {matriz[0,1:]}")

A matriz criada foi:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Acessando a ultima linha inteira: [2 3]
