# Indexação AVANÇADA


In [2]:
# Dado uma matriz de 3x3, use indexação booleana para acessar e imprimir apenas os elementos maiores que 5.
import numpy as np

# Criando o vetor
matriz = np.array([ [1,2,3], [4,5,6], [7,8,9]])

# Criando o boolean
index_booleano = matriz > 5

# Print
print(f"A matriz criada é:\n{matriz}")
print(f"Acessando todos os elementos da matriz maiores que 5 com boolean index: {matriz[index_booleano]}")

A matriz criada é:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Acessando todos os elementos da matriz maiores que 5 com boolean index: [6 7 8 9]
