# Indexação BÁSICA

In [2]:
# Use índices positivos e negativos para acessar e imprimir o elemento na segunda linha e última coluna de uma matriz 3x3
import numpy as np

# Criando a matriz
matriz = np.array([ [1,2,3], [4,5,6], [7,8,9]])

# Acessando o elemento
elemento_positivo_negativo = matriz[1, -1]

# Printando
print(F"A matriz criada foi:\n {matriz}")
print(f"Acessando o elemento por ordem positiva e negativa: {elemento_positivo_negativo}")


A matriz criada foi:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Acessando o elemento por ordem positiva e negativa: 6
