# Indexação BÁSICA

In [4]:
# Acesse o elemento da 2 linha e 3 coluna de uma matriz 3x3

import numpy as np
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"A matriz criada foi:\n{matriz}")
print(f"Acessando o elemento da 2 linha e 3 coluna da matriz: {matriz[1, 2]}")

A matriz criada foi:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Acessando o elemento da 2 linha e 3 coluna da matriz: 6
