# Indexação BÁSICA

In [2]:
# Dado uma matriz 3x3, acesse os elementos da 2 coluna e linha (meio da matriz)
import numpy as np

# Criando a matriz
matriz = np.array([ [1,2,3], [4,5,6], [7,8,9]])

# Acessando o meio da matriz
meio_matriz = matriz[1,1]

# Printando
print(f"A matriz criada foi:\n{matriz}")
print(f"Acessando o meio da matriz: {meio_matriz}")

A matriz criada foi:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Acessando o meio da matriz: 5
