# Indexação AVANÇADA

In [5]:
# Crie uma matriz 3x3 de 1 até 9 e com a BOOLEAN INDEX selecione apenas números maiores que 3 e menores que 7

import numpy as np

# Criando a matriz
matriz = np.array([ [1,2,3], [4,5,6], [7,8,9] ])

# Fazendo a indexação booleana
index_booleana = (matriz > 3) & (matriz < 7 )

# Printando
print(f"A matriz criada foi:\n{matriz}")
print(f"Os elementos da matriz maiores que 3 e menores que 7 são: {matriz[index_booleana]}")

A matriz criada foi:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Os elementos da matriz maiores que 3 e menores que 7 são: [4 5 6]
