# Indexação BÁSICA

In [7]:
# Use índices negativos para acessar e imprimir o elemento da última linha e primeira coluna a partir do final.
import numpy as np

# Criando a matriz
matriz = np.array([ [1,2,3], [4,5,6], [7,8,9]])

# Acessando o elemento
elemento = matriz[-1,-3]

# Printando
print(f"A matriz criada foi:\n{matriz}")
print(f"Acessando o elemento da última linha e primeira coluna partir do final: {elemento}")

A matriz criada foi:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Acessando o elemento da última linha e primeira coluna partir do final: 7
