# Indexação BÁSICA

In [1]:
# Acesse o elemento 10 da matriz

import numpy as np
matriz = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12], # 3 linha, 2 elemento -> (2,1)
                [13, 14, 15, 16]])


print(f"A matriz criada foi:\n{matriz}")
print(f"Acessando o elemento 10, presente na 3 linha e 2 coluna: {matriz[2,1]}")

A matriz criada foi:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Acessando o elemento 10, presente na 3 linha e 2 coluna: 10
