# Manipulacao de Array
#### Filtrando, acessando, criando e redimensionando arrays

In [4]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[arr > 3]) # Arr[arr] ele filtra por algo
print(arr[arr < 5])
print("Existe" if arr[arr == 2] else "Não existe")

[4 5 6 7 8 9]
[1 2 3 4]
Existe


In [14]:

print(arr[0,0]) # Primeiro elemento do 1 array
print(arr[1,1]) # Elemento do meio
print(arr[-1,-1]) # Ultimo elemento do ultimo array

1
5
9


In [13]:
arr1 = np.zeros((3,3)) # Cria uma matriz de 3x3 composta somente por 0
arr2 = np.ones((3,3)) # Cria uma matriz de 3x3 composta somente por 1
arr3 = np.full((2,2), 7) # Cria uma matrix 2x2 preenchida com numeros x (nesse caso 7)
print(f"Arr1:\n {arr1}\n\n Arr2:\n {arr2}\n\n Arr3:\n {arr3}")

Arr1:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Arr:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 Arr3:
 [[7 7]
 [7 7]]


In [29]:
arr4 = np.arange(12) # Cria um array unidimensional de 0-11 (1x11)
print(f"Antes:\n {arr4}\n\n")
arr_reshape = arr4.reshape(3,4) # Transforma em um array 3x4
print(f"Depois:\n {arr_reshape}")

Antes:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


Depois:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
