# Array manipulation
#### Filtering, accessing, creating and resizing arrays

In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[arr > 3]) # Arr[arr] it filters for something
print(arr[arr < 5])
print("Exists" if arr[arr == 2] else "Does not exist")

[4 5 6 7 8 9]
[1 2 3 4]
Exists


In [4]:
print(arr[0,0]) # First element of 1 array
print(arr[1,1]) # Middle element
print(arr[-1,-1]) # Last element of the last array

1
5
9


In [3]:
arr1 = np.zeros((3,3)) # Creates a 3x3 matrix composed only of 0
arr2 = np.ones((3,3)) # Creates a 3x3 matrix composed only of 1
arr3 = np.full((2,2), 7) # Creates a 2x2 matrix filled with numbers x (in this case 7)
print(f"Arr1:\n {arr1}\n\n Arr2:\n {arr2}\n\n Arr3:\n {arr3}")

Arr1:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Arr2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 Arr3:
 [[7 7]
 [7 7]]


In [2]:
arr4 = np.arange(12) # Creates a one-dimensional array from 0-11 (1x11)
print(f"Before:\n {arr4}\n\n")
arr_reshape = arr4.reshape(3,4) # Transforms into a 3x4 array
print(f"After:\n {arr_reshape}")

Before:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


After:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
