# Stacking arrays

##### -> Stacking the arrays vertical/horizontal

In [6]:
import numpy as np

arrA = np.array([[1, 2, 3] ,[4, 5, 6]]) #2 ROW, 3 COLUMNS
arrB = np.array([[7, 8, 9]]) #1 ROW, 3 COLUMNS
result = np.vstack((arrA , arrB)) # Stack the arrays (ARRAY A 0 WITH ARRAY B 0, ARRAY A 1 WITH ARRAT 1 B in vertical, IT'S NEED HAVE THE SAME NUMBER OF COLUMNS
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arrC = np.array([[0,1,2,3], [3,4,5,6]]) # 2 ROWS, 4 COLUNDS   
arrD = np.array([[7], [8]]) # 2 ROWS, 2 COLUMNS
result = np.hstack((arrC, arrD)) # Stack the arrays (ARRAY C 0 WITH ARRAY D 0, ARRAY C 1 WITH ARRAT 1 D) in horizontal, IT'S NEED TO HAVE THE SAME NUMBERS OF ROWS
print(result)

[[0 1 2 3 7]
 [3 4 5 6 8]]
