# Slicing AVANÇADO

In [4]:
# Dado um array 2D 3x3, extraia as duas últimas linhas e as duas últimas colunas com valores negativos.

import numpy as np
# Criando a matriz
matriz = np.array([ [10,20,30], [40,50,60], [70,80,90]])

# Fazendo o slicing
matriz_slicing = matriz[-2:, -2:]

# Printando
print(f"Matriz criada foi:\n{matriz}")
print(f"Nova matriz após o slicing:\n{matriz_slicing}")



Matriz criada foi:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Nova matriz após o slicing:
[[50 60]
 [80 90]]
