# Slicing AVANÇADO

In [ ]:
# Dado um array 2D 3x3, extraia uma submatriz que consiste nas linhas 1 e 2 e nas colunas 0 e 1.
import numpy as np
# Criando a matriz
matriz = np.array([ [10,20,30], [40,50,60], [70,80,90]])

# Fazendo o slicing
matriz_slicing = matriz[1:3, 0:2]

# Printando
print(f"Matriz criada foi:\n{matriz}")
print(f"Nova matriz após o slicing:\n{matriz_slicing}")


Matriz criada foi:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Nova matriz após o slicing:
[[40 50]
 [70 80]]
