# Slicing AVANÇADO

In [4]:
# Combine slicing com uma máscara booleana para selecionar elementos maiores que 50 das duas últimas linhas em uma submatriz.

import numpy as np

# Criando a matriz
matriz = np.array([ [10,20,30], [40,50,60], [70,80,90]])

# Fazendo o slicing e a máscara
matriz_slicing = matriz[-2:,:]
mask = matriz_slicing > 50

# Printando
print(f"Matriz criada foi:\n{matriz}")
print(f"Nova matriz após o slicing e máscara:\n{matriz_slicing[mask]}")


Matriz criada foi:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Nova matriz após o slicing e máscara:
[60 70 80 90]
