#  Slicing AVANÇADO


In [ ]:
# Acesse a matriz 2x2 central

import numpy as np
matriz = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])


print(f"A matriz criada foi:\n{matriz}")
print(f"Acessando apartir da 2 linha da 1 coluna:\n{matriz[1:3, 1:3]}")

A matriz criada foi:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Acessando apartir da 2 linha da 1 coluna:
[[ 6  7]
 [10 11]]
