# EXERCISE 1

#####   1. Criação de Matrizes e Acesso de Elementos
Crie uma matriz de 2x3 com os seguintes valores: [[1, 2, 3], [4, 5, 6]].
Acesse o elemento da segunda linha, terceira coluna.

In [4]:
import numpy as np

matrix = np.array([[1,2,3], [4,5,6]])
print(matrix[1,2])


6


# EXERCISE 2


#####  Crie duas matrizes 2x2, some e subtraia.



In [5]:
import numpy as np

matrix = np.array([[1,2] ,[3,4]])
matrix2 = np.array([[5,6] ,[7,8]])
print(f"A soma das duas matrizes são de\n {matrix + matrix2}\n")
print(f"A soma das duas matrizes são de\n {matrix - matrix2}\n")

A soma das duas matrizes são de
 [[ 6  8]
 [10 12]]

A soma das duas matrizes são de
 [[-4 -4]
 [-4 -4]]



# EXERCISE 3


#### Crie uma matriz 1D com os valores de 1 a 9 (ou seja, [1, 2, 3, 4, 5, 6, 7, 8, 9]). Realize um reshape dessa matriz para uma matriz 3x3.

In [9]:
import numpy as np
matrix1d = np.array([1,2,3,4,5,6,7,8,9])
print(f"Antes \n{matrix1d}\n")
matrix2d = matrix1d.reshape(3,3)
print(f"Depois \n{matrix2d}\n")

Antes 
[1 2 3 4 5 6 7 8 9]

Depois 
[[1 2 3]
 [4 5 6]
 [7 8 9]]



# EXERCISE 4


#### Crie uma matriz 3x3 da tabuada do 2, e utilize um filtro para acessar valores acima de 5

In [10]:
import numpy as np
matrix = np.array([[0,2,4], [6,8,10], [12,14,16]])
print(f"Os valores acima de 5 são {matrix[matrix > 5]}")

Os valores acima de 5 são [ 6  8 10 12 14 16]


# EXERCISE 5


#### Crie duas matrizes, empilhe elas verticalmente e horizontalmente

In [14]:
import numpy as np

matrix1 = np.array([[1,2], [2,3]])
matrix2 = np.array([[4,5], [6,7]])
vertical = np.vstack((matrix1, matrix2))
horizontal = np.hstack((matrix1, matrix2))
print(f"As matrizes empilhadas verticalmente:\n {vertical}")
print(f"As matrizes empilhadas horizontal:\n {horizontal}")

As matrizes empilhadas verticalmente:
 [[1 2]
 [2 3]
 [4 5]
 [6 7]]
As matrizes empilhadas horizontal:
 [[1 2 4 5]
 [2 3 6 7]]


# EXERCISE 6

#### Crie uma matrix 3x6 e divida em 2 sub-arrays

In [19]:
import numpy as np

matrix3x6 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18]])
split_array = np.split(matrix3x6, 2, axis= 1)
for i, sub_array in enumerate(split_array):
    print(f"Array {i +1}")
    print(sub_array)
    print()

Array 1
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]

Array 2
[[ 4  5  6]
 [10 11 12]
 [16 17 18]]

