# Math operations

In [2]:
# Dado duas matrizes de 3x3 elementos, calcule seu produto matricial

import numpy as np

# Criando os vetores
matriz1 = np.random.randint(1,10, size=(3,3))
matriz2 = np.random.randint(1,10, size=(3,3))

# Calculando o prduto escalar
produto_escalar = np.dot(matriz1, matriz2)

# Printando
print(f"As matrizes criadas foram, \nMatriz1:\n{matriz1}\nMatriz2:\n{matriz2}")
print(f"E seu produto matricial é de:\n{produto_escalar}")

As matrizes criadas foram, 
Matriz1:
[[2 4 5]
 [3 8 4]
 [3 9 3]]
Matriz2:
[[5 4 9]
 [1 4 8]
 [8 1 1]]
E seu produto matricial é de:
[[ 54  29  55]
 [ 55  48  95]
 [ 48  51 102]]
