# Math operations

In [4]:
# Dada uma matriz 3x3, calcule sua transposta.
import numpy as np

# Criando a matriz
matriz = np.array([ [1,2,3], [4,5,6]])

# Transposta
matriz_transposta = np.transpose(matriz)

# Printando
print(f"A matriz criada foi:\n{matriz}\ne sua transposta é:\n{matriz_transposta}")


A matriz criada foi:
[[1 2 3]
 [4 5 6]]
e sua transposta é:
[[1 4]
 [2 5]
 [3 6]]
