# Math operations

In [2]:
# Dado uma matriz 3x3, calcule a soma total, a soma das colunas e soma das linhas

import numpy as np

# Criando a matriz
matriz = np.random.randint(1,20, size=(3,3))

# Linhas, colunas e total
total = np.sum(matriz)
colunas = np.sum(matriz, axis = 0)
linhas = np.sum(matriz, axis = 1)

# Printando
print(f"A matriz criada foi:\n{matriz}")
print(f"A soma pelas colunas foi de: {colunas}, pelas linhas: {linhas}, já a soma total foi de: {total}")

A matriz criada foi:
[[ 8  6 12]
 [ 7  2 12]
 [ 1 16 13]]
A soma pelas colunas foi de: [16 24 37], pelas linhas: [26 21 30], já a soma total foi de: 77
