
# Math operations

In [8]:
# Dado uma matriz 3x3, printe o maior e menor número e sua média

import numpy as np

# Criando a matriz
matriz = np.random.randint(1,20, size=(3,3))

# Menor, maior e média
maior = np.max(matriz)
menor = np.min(matriz)
media = np.mean(matriz)

# Printando
print(f"A matriz criada foi:\n{matriz}")
print(f"A média da matriz foi de:{media:.2f}, seu valor máximo e mínimo respectivamente é: {maior}, {menor}")

A matriz criada foi:
[[ 8  9 17]
 [19 11  7]
 [12  3  8]]
A média da matriz foi de:10.44, seu valor máximo e mínimo respectivamente é: 19, 3
